# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # --------------------------------------------------
  # General settings
  # --------------------------------------------------
  config.vm.boot_timeout = 600
  config.vm.box          = "ubuntu/jammy64"
  config.vm.hostname     = "linux-practice"

  # Sync host folder
  config.vm.synced_folder ".", "/home/vagrant/carpeta_compartida"

  # --------------------------------------------------
  # Networking
  # --------------------------------------------------
  ip_address = "192.168.56.2"
  config.vm.network "private_network", ip: ip_address

  config.vm.network "forwarded_port",
                    guest: 22,
                    host:  2222,
                    id:    "ssh",
                    auto_correct: true

  # --------------------------------------------------
  # Provider-specific configuration for VirtualBox
  # --------------------------------------------------
  config.vm.provider "virtualbox" do |vb|
    # Use host DNS resolver
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]

    # Resources
    vb.memory       = "2048"
    vb.cpus         = 2
    vb.name         = "linux-practice"
    vb.linked_clone = true
    vb.gui          = false

    # Add 1 GB disk if not present
    unless File.exist?("./disk1.vdi")
      vb.customize ["createhd", "--filename", "./disk1.vdi", "--size", 1024]
    end

    vb.customize [
      "storageattach", :id,
      "--storagectl", "SCSI",
      "--port",       2,
      "--device",     0,
      "--type",       "hdd",
      "--medium",     "./disk1.vdi"
    ]
  end

  # --------------------------------------------------
  # SSH key & post-up message
  # --------------------------------------------------
  config.ssh.insert_key = true

  config.vm.post_up_message = <<-MSG
  ###########################################################################
  # VM lista. Para conectarte:
  #
  # 1) Ejecutar: vagrant ssh
  #
  # 2) O bien:
  #    ssh -i .vagrant/machines/default/virtualbox/private_key \
  #        vagrant@#{ip_address}
  ###########################################################################
  MSG

  # --------------------------------------------------
  # Provision scripts (external)
  # --------------------------------------------------
  config.vm.provision "shell", path: "script_Enable_ssh_password.sh"
  config.vm.provision "shell", privileged: false, path: "script_Fix_history.sh"

  # --------------------------------------------------
  # Inline provision: as root
  # --------------------------------------------------
  config.vm.provision "shell", inline: <<-SHELL
    whoami > /home/vagrant/README
  SHELL

  # --------------------------------------------------
  # Inline provision: as vagrant
  # --------------------------------------------------
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    mkdir -p /home/vagrant/repogit
    cd /home/vagrant/repogit
    git clone https://github.com/upszot/UTN-FRA_SO_onBording.git
  SHELL

  # --------------------------------------------------
  # DNS “blindaje”
  # --------------------------------------------------
  config.vm.provision "shell", inline: <<-SHELL
    systemctl stop systemd-resolved
    systemctl disable systemd-resolved
    rm -f /etc/resolv.conf
    echo "nameserver 8.8.8.8" >  /etc/resolv.conf
    echo "nameserver 1.1.1.1" >> /etc/resolv.conf
  SHELL

end
